export const QUERY_KEYS = {
  AUTH_ME: ['auth', 'me'],
  DASHBOARD_SUMMARY: ['dashboard', 'summary'],
  TRANSACTIONS: (params?: object) => ['finance', 'transactions', params],
  CATEGORIES: ['finance', 'categories'],
  BUDGETS: ['finance', 'budgets'],
  DEBT_PEOPLE: ['debts', 'people'],
  DEBT_RECORDS: (params?: object) => ['debts', 'records', params],
  DEBT_SETTLEMENTS: ['debts', 'settlements'],
  TODOS: (params?: object) => ['todos', params],
  GOALS: ['goals'],
  TIMELINE_EVENTS: ['timeline', 'events'],
  JOURNAL_ENTRIES: (params?: object) => ['journal', 'entries', params],
  MEDIA_ASSETS: (params?: object) => ['media', 'assets', params],
  MEDIA_ALBUMS: ['media', 'albums'],
  INTERESTS: ['interests'],
  VOCABULARY: (params?: object) => ['learning', 'vocabulary', params],
  FLASHCARDS: ['learning', 'flashcards'],
  MOCK_TESTS: ['learning', 'mock-tests'],
  STUDY_PLANS: ['learning', 'study-plans'],
  PROFILE: ['profile', 'me'],
  BIOGRAPHY: ['profile', 'biography'],
} as const;
