export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  FINANCE: '/finance',
  FINANCE_TRANSACTIONS: '/finance/transactions',
  FINANCE_BUDGETS: '/finance/budgets',
  DEBTS: '/debts',
  DEBTS_PEOPLE: '/debts/people',
  DEBTS_CALCULATOR: '/debts/calculator',
  TODOS: '/todos',
  GOALS: '/goals',
  TIMELINE: '/timeline',
  JOURNAL: '/journal',
  JOURNAL_NEW: '/journal/new',
  MEDIA: '/media',
  MEDIA_ALBUMS: '/media/albums',
  INTERESTS: '/interests',
  LEARNING: '/learning',
  LEARNING_VOCABULARY: '/learning/vocabulary',
  LEARNING_FLASHCARDS: '/learning/flashcards',
  LEARNING_MOCK_TESTS: '/learning/mock-tests',
  LEARNING_STUDY_PLAN: '/learning/study-plan',
  PROFILE: '/profile',
  PROFILE_BIOGRAPHY: '/profile/biography',
  SETTINGS: '/settings',
} as const;
